### ISSUE TITLE
Flag to automatically choose item if search term only returns one item

### ISSUE THREAD

**Issue by ykhurshid** [vn-ki/anime-downloader#125]
I would like a flag for the dl subcommand that automatically starts a download if the choosen search term (or url) returns only one item. My use case is that I would like to use this tool in conjunction with task spooler to automatically queue up shows. This would ideally be done with a command that once triggered requires no additional user input.

**Comment by hammadshifa97** [comment]
KissAnime is the art of Japanese animation intended primarily for adolescents and older people. That is why Japanese kissanime has gained immense popularity around the world. The success of the kissanime depends on the success of the manga (Japanese comics), so before you make a kissanime movie, look at how successful and popular the original manga was. When filming, the style of character rendering is usually preserved, but the plot can be changed, so many Latest APK advise reading the original version of the work you like.

KissAnime | Watch Online Anime Movies | KissAnime 2020
The word “[kissanime](https://medium.com/@hammadshifa97/kissanime-watch-online-anime-movies-kissanime-2020-cd84eb0365b4)” was born from the English animation, but due to the fact that the pronunciation of this word in Japanese and the more its spelling caused difficulties, they decided to reduce it as much as possible, and the word kissanime appeared. There are other theories according to which this word was born from the Latin anima, that is, “soul” or that in fact, this word comes from the French dessin kissanimé (“animation”). The Japanese themselves no longer remember how this word was born, so you and I can only build guesses and hypotheses.
The [kissanime](https://pcbeducation.com/kissanime/) was first shown in 1917 (directed by Junichi Kouchi), this comedy film lasted only two minutes and was called “Namakura-gatana”. The very first kissanime with sound was painted in 1933 under the name “Chikara to Onna no Yo no Naka” (Kenzō Masaoka). The tradition of rendering characters with big eyes was laid by the mangaka and animator Osama Tezuka, later he was called the “god of manga and kissanime”
Now you know a little about where the kissanime came from and who were the founders and pioneers. And now I suggest you plunge with your head and go to the magical world of [kissanime](https://pcbeducation.com/kissanime/). I promise you that you will definitely like this world and you can find a genre that will be of particular interest to you.

**Comment by Blatzar** [comment]
Using the flag -c 0 it automatically selects the only link if there's only one search result, could create another flag if needed. Just replace util.py search functions first lines with this.
```
def search(query, provider, choice=None):
    
    # Since this function outputs to stdout this should ideally be in
    # cli. But it is used in watch too. :(
    cls = get_anime_class(provider)
    search_results = cls.search(query)

    click.echo(format_search_results(search_results), err=True)

    if not search_results:
        logger.error('No such Anime found. Please ensure correct spelling.')

    if choice == 0 and len(search_results) == 1:
        val = 1
    else:
        if choice:
            val = choice
        else:
            val = click.prompt('Enter the anime no: ', type=int, default=1, err=True)
```

**Comment by vn-ki** [comment]
This issue has been fixed.
