### ISSUE TITLE
9anime changed their API again

### ISSUE THREAD

**Issue by Enderlein** [vn-ki/anime-downloader#13]
Once again, 9anime changed their API. Can't download or watch anything.

**Comment by vn-ki** [comment]
Oh my god. I think they are testing something new with their site. Might be one or two days before things cool down.

**Comment by KashTag** [comment]
Could they be doing it intentionally? So that people don't rely on stuff like this and instead directly use the website more?

**Comment by Enderlein** [comment]
I read somewhere in the issues page of DxCc's 9anime plugin (where the DD parameter is taken from) that these changes could be part of an attempt to subvert the aggressive ads on their site. It seems they succeeded in doing that this time because the ads no longer show through my ad blocker. Also, @vn-ki , I skimmed through their commits and issues and at no point does it seem like they elaborate on what DD is derived from, what it does, or what it's needed for. Any time anyone asks about it it looks like they just ignore the question, so trade secret, I guess?

**Comment by KashTag** [comment]
Does that mean now the focus is gonna be on other websites? Or are you guys gonna delve deeper into 9anime?

**Comment by vn-ki** [comment]
> Also, @vn-ki , I skimmed through their commits and issues and at no point does it seem like they elaborate on what DD is derived from, what it does, or what it's needed for. Any time anyone asks about it it looks like they just ignore the question, so trade secret, I guess?

I know. I remember doing it once before. Maybe it's a trade secret. I came very close to finding it today but then I had a lot of other things to do too. If you are feeling adventurous, I'll share what I know.

Since we are taking advantage of the ajax api of 9anime, the relevant code should centered around the ajax call. It is in `frontend/min/all.min.js`. (Checkout sources tab of developer tools). The problem is that the minified js is highly obfuscated. This makes the job a lot harder. (There was something else too, but I forgot now)

> Does that mean now the focus is gonna be on other websites? Or are you guys gonna delve deeper into 9anime?

Once 9anime stops changing, we can fix it. In the mean time, I am working on a fallback approach so that we can continue watching our dearest anime.

**Comment by vn-ki** [comment]
9anime has been fixed for now.

I have changed the watch command a lot. So your old watch lists will no longer work. Sorry for this. Hope you guys understand. Hopefully this will not repeat again.

**Comment by Enderlein** [comment]
I like the changes. The watch file wasn't plaintext with pickle, so I wasn't able to edit my watch list from my IDE. This should make things much easier to test.
