### ISSUE TITLE
downloaded episode numbers should be padded with zeros

### ISSUE THREAD

**Issue by bg1987** [vn-ki/anime-downloader#137]
The episodes downloaded aren't padded with zeros, resulting in a bad lexicographical order, so you cant just drag and drop them to a player, this is very annoying.

I have fixed this on my fork and submitted a pull request with the fix, your'e welcome to review it.

**Comment by vn-ki** [comment]
I'm not sure I want this as a feature. You can easily add this using `file-format` argument. 

That said, I don't have a strong opinion on not accepting it. If you (and others) could convince me, I'll merge.

**Comment by lsaa** [comment]
I'm for this. It's extremely annoying when you want to watch the whole series but it goes from episode 1 to episode 10, zero padding would fix that. It is a very specific problem because I download the entire series and open the entire folder with mpv. I think having it as an optional config would be ideal.

**Comment by vn-ki** [comment]
Closed in #136
