### ISSUE TITLE
animepahe has weird resolutions

### ISSUE THREAD

**Issue by vn-ki** [vn-ki/anime-downloader#210]
**Describe the bug**

Animepahe api returns resolutions like 692p, 1036p etc. We should think how to handle it

```
 {
'data': 
	{'65723': 
		{'692p': {'filesize': 405211235, 'crc32': 'a04be349', 'fansub': 'Reta
il', 'revision': '', 'disc': 'BD', 'url': 'https://kwik.cx/e/dasvaUC0j8xn', 'server': 'lux'}, 
		'1036p': {'filesize': 711722610, 'crc32': '9480ed25', 'fansub': 'Ret
ail', 'revision': '', 'disc': 'BD', 'url': 'https://kwik.cx/e/sjcJmankXfFk', 'server': 'lux'}}}}
```

**To reproduce**

```
anime dl 'nauroto' --provider animepahe --url
```

Choose one of the shippuden movies

**Comment by ngomile** [comment]
A convoluted fix probably involves dynamically setting both the qualities on the AnimepaheEpisode class and the AnimePahe class since if you don't do it for the latter an error will occur... on second thought this might also be a no go since the base Anime class checks to see if the quality entered by the user is one of the qualities in the QUALITIES list.

We could avoid the tight coupling between the Anime and AnimEpisode classes following the Single Responsibility Principal. Because right now the mere fact that the AnimEpisode class has to check on the qualities of the Anime class allows it to somehow skip over what it actually has available. So for AnimepaheEpisode maybe override the __init__ or just change the general structure.

Because this will persist even for other grabbers.

**Comment by vn-ki** [comment]
I would say to ignore the quality, as that's what we are doing for a lot of sites. Quality is not provided by a lot of sites, therefore we just ignore what the quality is right now. This is not a good option but I can't think of any other way which don't harm the user experience. 

Maybe we can somehow round the resolutions to standard ones? I don't want to expose these weird resolutions to the user.

**Comment by ngomile** [comment]
If the we ignore the qualities then we risk being unable to get any of the episodes. The program has done a good enough job ignoring them to begin with so that's okay I think. But perhaps we could have a base episode quality list some of the episode classes can decide if they are capable of fetching episodes?

**Comment by MichaelDavidJohnson** [comment]
Closing, resolution change would add dependencies. We should just use the resolutions provided by a provider. We successfully scraped the video, also AnimePahe is broken rn
