### ISSUE TITLE
Download Quality

### ISSUE THREAD

**Issue by LarrytheLog** [vn-ki/anime-downloader#28]
When using the program, if a quality of a certain video is unavailable it will move down to the closest one possible. If I was looking for Boku No Hero Acadamia and they didn't have 720, it would get 360. Then after it finds the 360p version, it downloads all the rest in 360p even if there is a better quality available. Not a big problemo just something I noticed.

**Comment by vn-ki** [comment]
Yeah. It falls back to the lowest quality and continues it through out the download (It was meant to be a feature :sweat_smile:). This is  because some old anime (Naruto, for example) has no 720p. Trying for a quality which does not exist for every episode did not make sense, but I did not anticipate an edge case like this.

Boku No Hero has an episode where only that one has no 720p?

Would you expect for it to try the preferred quality (here 720p) for every episode?

**Comment by LarrytheLog** [comment]
It would be nice if it could. I see why something like this was implemented but it is inconvenient when literally one anime episode of the series doesn't have 720p so the rest are 360p (Which is something that happened and is really annoying 😠). Thx for the help.

**Comment by vn-ki** [comment]
Sure thing. I'll make the change and push a release today.

**Comment by vn-ki** [comment]
Closed in https://github.com/vn-ki/anime-downloader/commit/c93dcaf1f714dd0e3bc633954d1e19ad0ab41fec
