### ISSUE TITLE
Update anime only if it is not completed

### ISSUE THREAD

**Issue by vn-ki** [vn-ki/anime-downloader#8]
`Watcher.update` should only update anime if the anime is still airing. To check if anime is still airing, `anime.meta['status'].lower() != 'completed'` can be used.

Relevant corner cases should be tested. (Movies, anime which may not have status(?)) 

The code which should be changed is linked below.

https://github.com/vn-ki/anime-downloader/blob/960b599a74dff199ce6d6435959ad32f3e09e655/anime_downloader/watch.py#L61-L68

**Comment by Enderlein** [comment]
I clicked through random anime and movies, both old and new, and everything had a status of either "Airing" or "Completed". Nothing had the status of "Upcoming" or anything like that and nothing was missing a status.

Just to be safe, though, I think it should check `anime.meta['Status'].lower() == 'airing'` instead of `anime.meta['Status'].lower() != 'completed'`. On the off-chance that something does have a strange status, `== airing` would only update things that aren't completed as intended while `!= completed` will update things that may have unusual statuses like "upcoming" or "cancelled" which wouldn't really do much.

**Comment by vn-ki** [comment]
Looks like this was fixed in #9.

Thanks @Enderlein! Next time you open a PR, please add `Closes #<relevent_issue_no>`. Doing that will make GitHub auto close the mentioned issue once the PR is merged!
